--- # Notification and handling Events
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: install nginx web server
    yum:
      name: nginx
      state: present
    notify:
    - enable and start the nginx service
    register: result
  - debug: var=result
  handlers:
  - name: enable and start the nginx service
    service:
      name: nginx
      enabled: yes
      state: restarted
