--- # Notification and handling Events
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name: remove nginx web server
    yum:
      name: nginx
      state: "{{ present}}"
    register: result
  - debug: var=result
#  - name: enable and start the nginx service
#    service:
#      name: nginx
#      state: restarted
